// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using br.ufc.mdcc.hpcshelf.platform.Maintainer;
using System;
using br.ufc.mdcc.hpc.storm.binding.task.TaskBindingBase;
using System.Threading;
using System.Collections.Generic;
using br.ufc.mdcc.hpcshelf.platform.maintainer.SAFeHost;
using mapreduce.countwords.Workflow;
using br.ufc.mdcc.hpcshelf.mapreduce.port.task.advance.ChunkReadyActionType;
using br.ufc.mdcc.hpcshelf.mapreduce.port.task.advance.PerformActionType;
using br.ufc.mdcc.hpcshelf.mapreduce.port.task.advance.ReadChunkActionType;
using br.ufc.mdcc.hpcshelf.mapreduce.port.task.TaskPortTypeAdvancePerform;
using br.ufc.mdcc.hpcshelf.mapreduce.port.task.TaskPortTypeAdvanceChunkReady;
using br.ufc.mdcc.hpcshelf.mapreduce.port.task.TaskPortTypeAdvanceReadChunk;
using br.ufc.mdcc.hpcshelf.mapreduce.port.task.TaskPortTypeAdvance;
using br.ufc.pargo.hpe.kinds;
using br.ufc.mdcc.hpcshelf.workflow.environment.SWLWorkflowBinding;
using br.ufc.mdcc.hpcshelf.workflow.environment.SWLPortType;


namespace mapreduce.countwords.WorkflowImpl 
{
    public class IWorkflowImpl<M> : br.ufc.pargo.hpe.kinds.Workflow, IWorkflow<M>
        where M : ISAFeHost
    {
        public override void main()
        {
            Console.WriteLine("WORKFLOW IMPL !!!");
            this.SWLOrchestration = SWLPort.Client.Workflow;
            base.main();
        }

        private ISWLWorkflowBinding swl_port = null;
        private ISWLWorkflowBinding SWLPort
        {
            get
            {
                return swl_port == null ? (ISWLWorkflowBinding)this.Services.getPort("swl_port") : swl_port;
            }
        }
    }
}
