// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using br.ufc.pargo.hpe.kinds;
using System.Threading;
using mapreduce.Application;
using mapreduce.Workflow;
using mapreduce.System;
using System;


namespace mapreduce.impl.SystemImpl {
    
    
	public class IRootImpl : br.ufc.pargo.hpe.kinds.Application, IRoot {
        
        private void Go(object o) 
		{
            ((Activate)(o)).go();
        }
        
        public override void main() 
		{
			Console.WriteLine ("ROOT 1");

            IApplication application = ((IApplication)(this.Services.getPort("application")));
			IWorkflow workflow = ((IWorkflow)(this.Services.getPort("workflow")));

			Console.WriteLine ("ROOT 2");

			Thread go_application = new Thread(new ParameterizedThreadStart(this.Go));
			Thread go_workflow = new Thread(new ParameterizedThreadStart(this.Go));

			Console.WriteLine ("ROOT 3");

            go_application.Start(application);        
            go_workflow.Start(workflow);
            
			Console.WriteLine ("ROOT 4");

			go_application.Join();
            go_workflow.Join(); 

			Console.WriteLine ("ROOT 5");
        }
    }
}
