// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using br.ufc.mdcc.hpcshelf.platform.Maintainer;
using System;
using br.ufc.mdcc.hpc.storm.binding.task.TaskBindingBase;
using System.Threading;
using br.ufc.mdcc.hpcshelf.mapreduce.port.task.TaskPortTypeAdvance;
//using br.ufc.mdcc.hpcshelf.mapreduce.port.task.TaskPortTypeData;
using System.Collections.Generic;
using br.ufc.mdcc.hpcshelf.platform.maintainer.SAFeHost;
using mapreduce.gust.iterative.tri.Workflow;


namespace mapreduce.gust.iterative.tril.WorkflowImpl {
    
    
	public class IWorkflowImpl<M> :br.ufc.pargo.hpe.kinds.Computation ,IWorkflow<M> 
		where M:ISAFeHost
	{
        
        public override void main()
        {
            Console.WriteLine("WORKFLOW IMPL !!!");
            this.SWLOrchestration = SWLPort.Client.Workflow;
            base.main();
        }

        private ISWLWorkflowBinding swl_port = null;
        private ISWLWorkflowBinding SWLPort
        {
            get
            {
                return swl_port == null ? (ISWLWorkflowBinding)this.Services.getPort("swl_port") : swl_port;
            }
        }

    }
}
