<?xml version="1.0" encoding="ASCII"?>
<component:hashComponent xmlns:component="http://www.example.org/HashComponent">
  <package>teste</package>
  <using>br.ufc.mdcc.hpcshelf.mapreduce.binding.task</using>
  <using>br.ufc.mdcc.hpc.storm.binding.environment</using>
  <using>br.ufc.mdcc.hpcshelf.mapreduce.port.environment</using>
  <using>br.ufc.mdcc.hpcshelf.mapreduce.computation</using>
  <using>br.ufc.mdcc.common</using>
  <using>br.ufc.mdcc.hpcshelf.mapreduce.custom</using>
  <kind>Computation</kind>
  <name>RRR</name>
  <innerComponent>
    <kind>Synchronizer</kind>
    <identifier>task_map</identifier>
    <type>
      <componentName>br.ufc.mdcc.hpcshelf.mapreduce.binding.task.TaskBindingAdvance</componentName>
    </type>
    <access>public</access>
    <exportActions>true</exportActions>
  </innerComponent>
  <innerComponent>
    <kind>Synchronizer</kind>
    <identifier>collect_pairs</identifier>
    <type>
      <componentName>br.ufc.mdcc.hpc.storm.binding.environment.EnvironmentBindingBase</componentName>
      <parameter>
        <identifier>client_port_type</identifier>
        <constraint>
          <componentConstraint>br.ufc.mdcc.hpcshelf.mapreduce.port.environment.PortTypeIterator</componentConstraint>
        </constraint>
      </parameter>
      <parameter>
        <identifier>server_port_type</identifier>
        <constraint>
          <componentConstraint>br.ufc.mdcc.hpcshelf.mapreduce.port.environment.PortTypeIterator</componentConstraint>
        </constraint>
      </parameter>
    </type>
    <access>public</access>
    <exportActions>true</exportActions>
  </innerComponent>
  <innerComponent>
    <kind>Synchronizer</kind>
    <identifier>feed_pairs</identifier>
    <type>
      <componentName>br.ufc.mdcc.hpc.storm.binding.environment.EnvironmentBindingBase</componentName>
      <parameter>
        <identifier>client_port_type</identifier>
        <constraint>
          <componentConstraint>br.ufc.mdcc.hpcshelf.mapreduce.port.environment.PortTypeIterator</componentConstraint>
        </constraint>
      </parameter>
      <parameter>
        <identifier>server_port_type</identifier>
        <constraint>
          <componentConstraint>br.ufc.mdcc.hpcshelf.mapreduce.port.environment.PortTypeIterator</componentConstraint>
        </constraint>
      </parameter>
    </type>
    <access>public</access>
    <exportActions>true</exportActions>
  </innerComponent>
  <innerComponent>
    <kind>Computation</kind>
    <identifier>mapper</identifier>
    <type>
      <componentName>br.ufc.mdcc.hpcshelf.mapreduce.computation.Mapper</componentName>
      <publicInnerComponent>task_map</publicInnerComponent>
      <publicInnerComponent>collect_pairs</publicInnerComponent>
      <publicInnerComponent>feed_pairs</publicInnerComponent>
      <parameter>
        <identifier>output_value_type</identifier>
        <variable>OMV</variable>
        <constraint>
          <componentConstraint>br.ufc.mdcc.common.Data</componentConstraint>
        </constraint>
      </parameter>
      <parameter>
        <identifier>platform</identifier>
        <variable>P</variable>
        <constraint>
          <componentConstraint>br.ufc.mdcc.common.Platform</componentConstraint>
        </constraint>
      </parameter>
      <parameter>
        <identifier>input_key_type</identifier>
        <variable>IMK</variable>
        <constraint>
          <componentConstraint>br.ufc.mdcc.common.Data</componentConstraint>
        </constraint>
      </parameter>
      <parameter>
        <identifier>input_value_type</identifier>
        <variable>IMV</variable>
        <constraint>
          <componentConstraint>br.ufc.mdcc.common.Data</componentConstraint>
        </constraint>
      </parameter>
      <parameter>
        <identifier>map_function</identifier>
        <variable>MF</variable>
        <constraint>
          <componentConstraint>br.ufc.mdcc.hpcshelf.mapreduce.custom.MapFunction</componentConstraint>
          <parameter>
            <identifier>input_key_type</identifier>
            <variable>IMK</variable>
            <constraint>
              <componentConstraint>br.ufc.mdcc.common.Data</componentConstraint>
            </constraint>
          </parameter>
          <parameter>
            <identifier>output_item_value_type</identifier>
            <variable>OMV</variable>
            <constraint>
              <componentConstraint>br.ufc.mdcc.common.Data</componentConstraint>
            </constraint>
          </parameter>
          <parameter>
            <identifier>input_value_type</identifier>
            <variable>IMV</variable>
            <constraint>
              <componentConstraint>br.ufc.mdcc.common.Data</componentConstraint>
            </constraint>
          </parameter>
          <parameter>
            <identifier>output_item_key_type</identifier>
            <variable>OMK</variable>
            <constraint>
              <componentConstraint>br.ufc.mdcc.common.Data</componentConstraint>
            </constraint>
          </parameter>
        </constraint>
      </parameter>
      <parameter>
        <identifier>output_key_type</identifier>
        <variable>OMK</variable>
        <constraint>
          <componentConstraint>br.ufc.mdcc.common.Data</componentConstraint>
        </constraint>
      </parameter>
    </type>
    <access>private</access>
    <exportActions>true</exportActions>
  </innerComponent>
</component:hashComponent>